import { useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { APP_THEMES, getThemeCanvas, getThemePalette } from '../constants';
import { useAppContext } from '../AppContext';
import { exportJSON, exportPNG, exportSVG } from '../storage/persistence';
import type { AppearanceMode, CanvasPattern } from '../types';
import { CanvasColorPicker } from './CanvasColorPicker';

const MoonIcon = () => <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.5 14.3A8.5 8.5 0 0 1 9.7 3.5 8.5 8.5 0 1 0 20.5 14.3Z"/></svg>;
const EyeIcon = ({ hidden = false }: { hidden?: boolean }) => <svg viewBox="0 0 24 24"><path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z"/><circle cx="12" cy="12" r="2.5"/>{hidden && <path d="m4 4 16 16"/>}</svg>;
const LockIcon = ({ locked = false }: { locked?: boolean }) => <svg viewBox="0 0 24 24"><rect x="5" y="10" width="14" height="10" rx="2"/><path d={locked ? 'M8 10V7a4 4 0 0 1 8 0v3' : 'M8 10V7a4 4 0 0 1 7.2-2.4'}/></svg>;
const PanelIcon = () => <svg viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="14" rx="2"/><path d="M14 5v14"/></svg>;
const GearIcon = () => <svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1-2.8 2.8-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.6v.2h-4V21a1.7 1.7 0 0 0-1-1.6 1.7 1.7 0 0 0-1.9.3l-.1.1L4.2 17l.1-.1a1.7 1.7 0 0 0 .3-1.9A1.7 1.7 0 0 0 3 14H2.8v-4H3a1.7 1.7 0 0 0 1.6-1 1.7 1.7 0 0 0-.3-1.9L4.2 7 7 4.2l.1.1a1.7 1.7 0 0 0 1.9.3A1.7 1.7 0 0 0 10 3V2.8h4V3a1.7 1.7 0 0 0 1 1.6 1.7 1.7 0 0 0 1.9-.3l.1-.1L19.8 7l-.1.1a1.7 1.7 0 0 0-.3 1.9 1.7 1.7 0 0 0 1.6 1h.2v4H21a1.7 1.7 0 0 0-1.6 1Z"/></svg>;

export function WorkspacePanel({ onOpenSettings }: { onOpenSettings: () => void }) {
  const { state, dispatch } = useAppContext();
  const [collapsed, setCollapsed] = useState(() => window.matchMedia('(max-width: 900px)').matches);
  const [name, setName] = useState('Untitled');
  const [pageName, setPageName] = useState('Page 1');
  const [backgroundOpen, setBackgroundOpen] = useState(false);
  const [shareOpen, setShareOpen] = useState(false);
  const [themeOpen, setThemeOpen] = useState(false);
  const [overflowOpen, setOverflowOpen] = useState(false);
  const themeWrapRef = useRef<HTMLDivElement>(null);
  const palette = getThemePalette(state.themeId);
  useEffect(() => {
    const mobile = window.matchMedia('(max-width: 900px)');
    const collapseOnMobile = (event: MediaQueryListEvent) => { if (event.matches) setCollapsed(true); };
    mobile.addEventListener('change', collapseOnMobile);
    return () => mobile.removeEventListener('change', collapseOnMobile);
  }, []);
  useEffect(() => { const close = (event: PointerEvent) => { const target = event.target as Element; if (!themeWrapRef.current?.contains(target) && !target.closest?.('.workspace-theme-wrap')) setThemeOpen(false); if (!target.closest?.('.workspace-overflow-wrap')) setOverflowOpen(false); }; window.addEventListener('pointerdown', close); return () => window.removeEventListener('pointerdown', close); }, []);
  const setAppearance = (mode: AppearanceMode) => {
    const resolvedTheme = mode === 'system' ? (matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light') : mode;
    dispatch({ type:'SET_APPEARANCE_MODE', mode, resolvedTheme, canvasBackground:getThemeCanvas(palette.id, resolvedTheme) });
  };
  const themeMenu = themeOpen ? createPortal(<div className="workspace-theme-menu" ref={themeWrapRef}><div className="workspace-appearance-tabs"><button className={state.appearanceMode === 'system' ? 'active' : ''} onClick={() => setAppearance('system')}>System</button><button className={state.appearanceMode === 'light' ? 'active' : ''} onClick={() => setAppearance('light')}>Light</button><button className={state.appearanceMode === 'dark' ? 'active' : ''} onClick={() => setAppearance('dark')}>Dark</button></div><div className="workspace-theme-grid">{APP_THEMES.map((theme) => <button key={theme.id} className={state.themeId === theme.id ? 'active' : ''} onClick={() => { dispatch({ type:'SET_THEME_ID', themeId:theme.id, appearance:state.theme, canvasBackground:getThemeCanvas(theme.id, state.theme) }); setThemeOpen(false); }}><i style={{ background:getThemeCanvas(theme.id, state.theme) }}><b style={{ background:theme.accent }}/><span/><em/></i><strong>{theme.name}</strong>{state.themeId === theme.id && <small>✓</small>}</button>)}</div></div>, document.body) : null;

  if (collapsed) return <nav className="workspace-rail glass-panel" aria-label="Workspace shortcuts"><button onClick={() => setCollapsed(false)} aria-label="Open workspace panel"><PanelIcon/><b>{state.layers.length}</b></button><span/><button onClick={() => setAppearance(state.theme === 'light' ? 'dark' : 'light')} aria-label={`Switch to ${state.theme === 'light' ? 'dark' : 'light'} appearance`}><MoonIcon/></button><button onClick={onOpenSettings} aria-label="Settings"><GearIcon/></button><button aria-label="Share live session"><svg viewBox="0 0 24 24"><path d="M8.5 15.5a5 5 0 0 1 0-7M5.5 18.5a9 9 0 0 1 0-13M15.5 8.5a5 5 0 0 1 0 7M18.5 5.5a9 9 0 0 1 0 13"/><circle cx="12" cy="12" r="2"/></svg></button></nav>;
  return <aside className="workspace-panel glass-panel" aria-label="Pages and canvas settings">
    <header><input value={name} onChange={(event) => setName(event.target.value)} aria-label="Drawing name"/><span>Saved</span><div className="workspace-theme-wrap"><button className="workspace-theme-mode" onClick={() => setAppearance(state.theme === 'light' ? 'dark' : 'light')} aria-label={`Switch to ${state.theme === 'light' ? 'dark' : 'light'} appearance`}><MoonIcon/></button><i/><button className="workspace-theme-menu-trigger" onClick={() => setThemeOpen((open) => !open)} aria-expanded={themeOpen} aria-label="Open colour theme menu"><svg className="chevron" viewBox="0 0 12 12"><path d="m3 4.5 3 3 3-3"/></svg></button>{themeMenu}</div><div className="workspace-overflow-wrap"><button onClick={() => setOverflowOpen((open) => !open)} aria-label="More options">•••</button>{overflowOpen && <div className="workspace-overflow-menu"><button onClick={onOpenSettings}><GearIcon/>Settings</button><button onClick={() => setShareOpen(true)}>Share & export</button></div>}</div><button onClick={() => setCollapsed(true)} aria-label="Collapse panel"><PanelIcon/></button></header>
    <section className="workspace-section pages-section"><div className="workspace-heading">Pages <button aria-label="Add page">+</button></div><button className="page-card active"><span>1</span><strong>1</strong></button></section>
    <div className="page-name"><input value={pageName} onChange={(event) => setPageName(event.target.value)} aria-label="Page name" /></div>
    <section className="workspace-section layers-section"><div className="workspace-heading">Layers <button aria-label="Add layer" onClick={() => dispatch({ type:'ADD_LAYER' })}>+</button></div><div className="layers-list">{[...state.layers].reverse().map((layer) => { const index = state.layers.findIndex((item) => item.id === layer.id); return <div className={`layer-row ${state.activeLayerId === layer.id ? 'active' : ''}`} key={layer.id} onClick={() => dispatch({ type:'SET_ACTIVE_LAYER', id:layer.id })}><button title={layer.visible ? 'Hide layer' : 'Show layer'} onClick={(event) => { event.stopPropagation(); dispatch({ type:'UPDATE_LAYER', id:layer.id, updates:{ visible:!layer.visible } }); }}><EyeIcon hidden={!layer.visible}/></button><button title={layer.locked ? 'Unlock layer' : 'Lock layer'} onClick={(event) => { event.stopPropagation(); dispatch({ type:'UPDATE_LAYER', id:layer.id, updates:{ locked:!layer.locked } }); }}><LockIcon locked={layer.locked}/></button><input value={layer.name} aria-label="Layer name" onClick={(event) => event.stopPropagation()} onChange={(event) => dispatch({ type:'UPDATE_LAYER', id:layer.id, updates:{ name:event.target.value } })}/><small>{state.elements.filter((el) => (el.layerId || 'layer-1') === layer.id).length}</small><div className="layer-order"><button disabled={index === state.layers.length - 1} aria-label={`Move ${layer.name} up`} onClick={(event) => { event.stopPropagation(); dispatch({ type:'MOVE_LAYER', id:layer.id, direction:'up' }); }}>⌃</button><button disabled={index === 0} aria-label={`Move ${layer.name} down`} onClick={(event) => { event.stopPropagation(); dispatch({ type:'MOVE_LAYER', id:layer.id, direction:'down' }); }}>⌄</button></div>{state.layers.length > 1 && <button className="layer-delete" aria-label={`Delete ${layer.name}`} title={`Delete ${layer.name}`} onClick={(event) => { event.stopPropagation(); dispatch({ type:'DELETE_LAYER', id:layer.id }); }}><svg viewBox="0 0 24 24"><path d="M4 7h16M9 7V4h6v3M7 7l1 13h8l1-13M10 11v5M14 11v5"/></svg></button>}</div>; })}</div></section>
    <section className={`workspace-accordion ${backgroundOpen ? 'open' : ''}`}><button onClick={() => setBackgroundOpen((open) => !open)}><span>Background</span><b>›</b></button>{backgroundOpen && <div className="workspace-accordion-body"><div className="workspace-pattern-grid">{(['blank','ruled','grid','dotted'] as CanvasPattern[]).map((pattern) => <button key={pattern} className={state.canvasPattern === pattern ? 'active' : ''} onClick={() => dispatch({ type:'SET_CANVAS_PATTERN', pattern })}>{pattern}</button>)}</div><label>Pattern visibility <span>{Math.round(state.patternOpacity * 100)}%</span></label><input className="pattern-opacity" type="range" min="0.04" max="0.5" step="0.02" value={state.patternOpacity} onChange={(event) => dispatch({ type:'SET_PATTERN_OPACITY', opacity:Number(event.target.value) })}/><div className="canvas-background-row"><span>Canvas background</span><CanvasColorPicker value={state.canvasBackground} onChange={(color) => dispatch({ type:'SET_CANVAS_BACKGROUND', color })}/></div></div>}</section>
    <section className={`workspace-accordion ${shareOpen ? 'open' : ''}`}><button onClick={() => setShareOpen((open) => !open)}><span>Share & export</span><b>›</b></button>{shareOpen && <div className="workspace-export"><button onClick={() => exportPNG(state.elements, state.theme)}><svg viewBox="0 0 24 24"><path d="M12 3v12m0 0 4-4m-4 4-4-4M5 19h14"/></svg><span>Export PNG</span></button><button onClick={() => exportSVG(state.elements, state.theme)}><svg viewBox="0 0 24 24"><path d="M7 3h7l4 4v14H7zM14 3v5h5"/><path d="m10 15 2-2 2 2"/></svg><span>Export SVG</span></button><button onClick={() => exportJSON(state.elements)}><svg viewBox="0 0 24 24"><path d="M5 7h14v14H5zM8 3h8v4H8z"/><path d="M9 12h6M9 16h4"/></svg><span>Save drawing</span></button></div>}</section>
  </aside>;
}
